### ISSUE TITLE
Corrupted recordings on iOS

### ISSUE THREAD

**Issue by LucasCoelho** [smartlook/smartlook-mobile-issue-tracker#114]
**Platform**
iOS

**Technology**
SwiftUI

**Build instructions [optional]**
n/a

**Rendering [optional]**
n/a

**Affected devices [optional]**
iPhone10,1
iPhone13,1
iPhone14,3

**Smartlook SDK version**
1.8.0

**Summary**
When trying to play the recordings on Smartlook dashboard I get the message `The recording is corrupted. We're unable to show you the recording right now.` 

**Steps to reproduce [optional]**
n/a

**Example Project [optional]**
n/a

**Relevant logs and/or screenshots**
n/a

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , few followup questions: 

1. are all recordings corrupted, or just some of them?
2. are the recordings fully corrupted, or partially visible?

Thanks.

**Comment by LucasCoelho** [comment]
Hi @pavel-kroh-smartlook 
1. Several recordings are corrupted but not all of them
2. Fully corrupted

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , thanks a lot for the details. It seems like backend issue. It is late evening here, I'll share the issue with my colleagues tomorrow morning. Sorry for the inconvenience.

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , some records get corrupted in our backend for yet unknown reason, the backend team works on it.

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , there is new version of SDK 1.8.3 released. It fixes several issues, some of them that might cause session corruption.

**Comment by SenNeonoveNoci** [comment]
@LucasCoelho We hope that your issue is fixed now. If you have any further issues, feel free to reopen this issue.

**Comment by LucasCoelho** [comment]
@SenNeonoveNoci We're still experiencing the same issues with SDK 1.8.3. Can you reopen this issue please?

**Comment by mithilesh-parmar** [comment]
@SenNeonoveNoci Same is the case with me. Some of the users in US have recording of 60-240 mins and they are all corrupted. Please look into this we are not able to analyse our potential paying customers.
