### ISSUE TITLE
App freeze and get crash for `trackCustomEvent`.

### ISSUE THREAD

**Issue by uasghar-smile** [smartlook/smartlook-mobile-issue-tracker#150]
**React native**
Hi I am using Smartlook SDK Wrapper in my react native project. So, I am using it for both iOS & Android.

**Build instructions**
React native: 0.64.0,
smartlook-react-native-wrapper: 1.2.5
Xcode: 13.3
node: v16.14.2
npm: 8.6.0
yarn: 1.22.17

**Affected devices**
Once it occurs then it will be for every iOS device

**Smartlook SDK version**
smartlook-react-native-wrapper: 1.2.5

**Summary**
After successfully complied code through Xcode when app tries to start it stuck because in the very first screen I am initiating the Smartlook SDK as:
```
Smartlook.setupAndStartRecording(SMART_LOOK_KEY);
```

and the crash will comes when `trackCustomEvent` will calls as:

```
Smartlook.trackCustomEvent("searched_dentist", { user_id: global?.user?.email });
```

**Steps to reproduce**
Just install package and pods and run the `trackCustomEvent`

**Relevant logs and/or screenshots**
Xcode get crash and app get stuck:
```
#12    0x00000001035592a1 in __36-[RNSmartlook trackCustomEvent:map:]_block_invoke at /Users/usamaasghar/workspace/smile-mobile-app/node_modules/smartlook-react-native-wrapper/ios/RNSmartlook.m:315
```
<img width="1440" alt="Screenshot 2022-04-21 at 10 03 43 AM" src="https://user-images.githubusercontent.com/102786004/164375882-0e810734-bf6f-4604-a004-81a1389d7616.png">

**Comment by uasghar-smile** [comment]
Hi @krystofcelba please help me out in this issue.

**Comment by uasghar-smile** [comment]
Any update here on this issue @krystofcelba @pavel-kroh-smartlook

**Comment by krystofcelba** [comment]
Hey @uasghar-smile,
could you please update to `v1.2.6`? It should be fixed there.

**Comment by uasghar-smile** [comment]
Hi @krystofcelba, I tried to upgrade the version but still gets the same error.

**Comment by SenNeonoveNoci** [comment]
@uasghar-smile  We are closing our GitHub issues and migrating all issue resolving to Intercom. Can you please write a follow up to  **support@smartlook.com**.
