### ISSUE TITLE
NullPointerException in React Native Android from Smartlook causing crash for ~50% of users, Smartlook unusable

### ISSUE THREAD

**Issue by AndrewMorsillo** [smartlook/smartlook-mobile-issue-tracker#25]
**Platform**
Android

**Technology**
React Native 0.63.3

**Smartlook SDK version**
"smartlook-react-native-wrapper": "^0.34.0",

**Summary**
Release mode crash `java.lang.NullPointerException Attempt to invoke virtual method 'android.app.Activity a.b.a.a.e.d.d()' on a null object reference `

Happens to nearly 50% of our users making app stability unacceptably poor.

Despite the obfuscated stack trace I've confirmed this is a Smartlook problem. I made a build with Smartlook removed and this crash (and a few others) disappeared and stability is back near 100%. 

**Steps to reproduce [optional]**
Unknown, appears to happen randomly in release on the play store. Happens across all Android device manufacturers and Android versions.

**Relevant logs and/or screenshots**
```
java.lang.NullPointerException Attempt to invoke virtual method 'android.app.Activity a.b.a.a.e.d.d()' on a null object reference 
    SourceFile:1 a.b.a.a.e.c.f
    SourceFile:53 a.b.a.a.e.i.g.c.a
    SourceFile:5 a.b.a.a.e.i.g.c.i
    SourceFile:292 a.b.a.a.e.i.g.b.a
    SourceFile:1 a.b.a.a.e.i.g.f.b.dispatchTouchEvent
    DecorView.java:687 com.android.internal.policy.DecorView.dispatchTouchEvent
    View.java:14644 android.view.View.dispatchPointerEvent
    ViewRootImpl.java:6522 android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent
    ViewRootImpl.java:6309 android.view.ViewRootImpl$ViewPostImeInputStage.onProcess
    ViewRootImpl.java:5747 android.view.ViewRootImpl$InputStage.deliver
    ViewRootImpl.java:5800 android.view.ViewRootImpl$InputStage.onDeliverToNext
    ViewRootImpl.java:5766 android.view.ViewRootImpl$InputStage.forward
    ViewRootImpl.java:5922 android.view.ViewRootImpl$AsyncInputStage.forward
    ViewRootImpl.java:5774 android.view.ViewRootImpl$InputStage.apply
    ViewRootImpl.java:5979 android.view.ViewRootImpl$AsyncInputStage.apply
    ViewRootImpl.java:5747 android.view.ViewRootImpl$InputStage.deliver
    ViewRootImpl.java:5800 android.view.ViewRootImpl$InputStage.onDeliverToNext
    ViewRootImpl.java:5766 android.view.ViewRootImpl$InputStage.forward
    ViewRootImpl.java:5774 android.view.ViewRootImpl$InputStage.apply
    ViewRootImpl.java:5747 android.view.ViewRootImpl$InputStage.deliver
    ViewRootImpl.java:8906 android.view.ViewRootImpl.deliverInputEvent
    ViewRootImpl.java:8767 android.view.ViewRootImpl.doProcessInputEvents
    ViewRootImpl.java:8720 android.view.ViewRootImpl.enqueueInputEvent
    ViewRootImpl.java:9042 android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent
    InputEventReceiver.java:194 android.view.InputEventReceiver.dispatchInputEvent
    InputEventReceiver.java:-2 android.view.InputEventReceiver.nativeConsumeBatchedInputEvents
    InputEventReceiver.java:183 android.view.InputEventReceiver.consumeBatchedInputEvents
    ViewRootImpl.java:8982 android.view.ViewRootImpl.doConsumeBatchedInput
    ViewRootImpl.java:9069 android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run
    Choreographer.java:996 android.view.Choreographer$CallbackRecord.run
    Choreographer.java:794 android.view.Choreographer.doCallbacks
    Choreographer.java:722 android.view.Choreographer.doFrame
    Choreographer.java:981 android.view.Choreographer$FrameDisplayEventReceiver.run
    Handler.java:883 android.os.Handler.handleCallback
    Handler.java:100 android.os.Handler.dispatchMessage
    Looper.java:237 android.os.Looper.loop
    ActivityThread.java:7814 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invoke
    RuntimeInit.java:493 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run
    ZygoteInit.java:1068 com.android.internal.os.ZygoteInit.main
```

**Comment by adamblack** [comment]
Hi @AndrewMorsillo ,

tomorrow we are going to release new patch. Apart from this issue, patch will handle also issue 24 that you created few days ago. We are really sorry for any inconvenience caused.

**Comment by adamblack** [comment]
Fixed in newest version

**Comment by AndrewMorsillo** [comment]
@adamblack please reopen this issue. I updated to the latest version of smartlook react native and the issue persists. It's crashing for the majority of my users. I have to remove Smartlook until this is resolved.

**Comment by alon7** [comment]
This was a major problem for us as well and it should have been communicated via email to all of your users. we've have seen 50% crashes on google play and weren't sure what's going on. unfortunately, we will have to remote smartlook from our app because of that.
